import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useDarkMode } from './theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [theme] = typeof window !== 'undefined' ? useDarkMode() : ['light'];
  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
